# Generated by Django 3.1 on 2020-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField(max_length=500)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=60)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
